excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://gangnamrice9.github.io
title: Rice Rocca
tagline: Most illegal person on the web.
description: Fixing the world 7 or 8 problems at a time.
paginate: 5
